# Generated by Django 5.2.4 on 2025-07-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorespuesta',
            name='calificacion',
            field=models.IntegerField(default=1),
        ),
    ]
