# Generated by Django 5.2.4 on 2025-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_usuariorespuesta_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorespuesta',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
